# Generated by Django 5.0.1 on 2024-02-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Post Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author name')),
                ('author_img', models.ImageField(upload_to='images/author', verbose_name='Author image')),
                ('author_about', models.CharField(max_length=500, verbose_name='About author')),
                ('date', models.DateTimeField(verbose_name='Publication date')),
                ('description1', models.TextField(verbose_name='Post text')),
                ('img1', models.ImageField(upload_to='images/%Y', verbose_name='Image')),
                ('description2', models.TextField(verbose_name='Post text')),
                ('img2', models.ImageField(upload_to='images/%Y', verbose_name='Image')),
                ('description3', models.TextField(verbose_name='Post text')),
                ('img3', models.ImageField(upload_to='images/%Y', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP-address')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Post')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('body', models.TextField(max_length=2000, verbose_name='Comment')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Comment Time')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
